Feature/logger
LerianStudio/midaz-console pull request #65
Opened 2024-11-29 19:37 UTC by paulofdev

# Midaz Console Pull Request Checklist

## Pull Request Type

[//]: # 'Check the appropriate box for the type of pull request.'

- [ ] UI
- [x] Core (Business Lógic)
- [ ] Security
- [ ] internationalization
- [ ] Pipeline
- [ ] Documentation

## Checklist

Please check each item after it's completed.

- [x] I have tested these changes locally.
- [ ] I have updated the documentation accordingly.
- [ ] I have added necessary comments to the code, especially in complex areas.
- [ ] I have ensured that my changes adhere to the project's coding standards.
- [ ] I have checked for any potential security issues.
- [ ] I have ensured that all tests pass.
- [ ] I have updated the version appropriately (if applicable).
- [ ] I have confirmed this code is ready for review.

## Additional Notes

[//]: # 'Add any additional notes, context, or explanation that could be helpful for reviewers.'

## Obs: Please, always remember to target your PR to develop branch instead of main.

2024-12-10 17:19 UTC, caioaletroca requested changes

2024-12-10 17:49 UTC, caioaletroca requested changes

2024-12-10 17:49 UTC, caioaletroca commented on src/app/api/organizations/[id]/ledgers/[ledgerId]/portfolios/[portfolioId]/route.ts
> +  if (!midazId) {
I don't think you need to check for the midazId, since you are literally creating it right before this execution (on the middleware).

2024-12-10 17:49 UTC, caioaletroca commented on src/core/application/mappers/portfolio-mapper.ts
> +    RequestContextManager.addEvent({
I don't think we should log mappers, Unit test should prevent mappers from throwing errors.

2024-12-10 18:07 UTC, paulofdev commented on src/core/application/mappers/portfolio-mapper.ts
> +    RequestContextManager.addEvent({
Ok!

2024-12-10 18:07 UTC, paulofdev commented on src/core/infrastructure/container-registry/container-registry.ts
> +container.bind<ILogger>(TYPES.ILogger).to(PinoLogger).inSingletonScope()
This was leftovers from the implementation POC

2024-12-10 18:21 UTC, paulofdev commented on src/core/infrastructure/midaz/portfolios/midaz-create-portfolio-repository.ts
> +    console.log('midazId', midazId)
removed

2024-12-10 18:22 UTC, paulofdev commented on src/lib/logger/pino-logger.ts
> +    // EventEmitter.defaultMaxListeners = 20
removed

2024-12-10 18:26 UTC, paulofdev commented on src/app/api/organizations/[id]/ledgers/[ledgerId]/portfolios/[portfolioId]/route.ts
> +  if (!midazId) {
removed

2024-12-10 20:49 UTC, caioaletroca approved these changes

2024-12-11 19:12 UTC, augusto-draxx commented on src/app/api/organizations/[id]/ledgers/[ledgerId]/portfolios/[portfolioId]/route.ts
> +        console.error('Error deleting portfolio', error)
Remover console.log()

2024-12-11 19:14 UTC, augusto-draxx commented on src/app/api/organizations/[id]/ledgers/[ledgerId]/portfolios/[portfolioId]/route.ts
> +        console.error('Error updating portfolio', error)
Remover console.log()

2024-12-11 19:36 UTC, augusto-draxx commented on src/app/api/organizations/[id]/ledgers/[ledgerId]/portfolios/[portfolioId]/route.ts
> +        console.error('Error getting portfolio', error)
Remover console.log()

2024-12-11 21:17 UTC, augusto-draxx commented on src/core/application/mappers/portfolio-mapper.ts
> +import { RequestContextManager } from '@/lib/logger/request-context'
Remover import não utilizado.

2024-12-11 21:19 UTC, augusto-draxx commented on src/core/infrastructure/midaz/portfolios/midaz-update-portfolio-repository.ts
> +        'X-Midaz-Id': midazId
O nome do header não é Midaz-Id? Segundo a documentação, seria esse o nome do atributo do header.

2024-12-11 21:20 UTC, augusto-draxx commented on src/core/infrastructure/midaz/portfolios/midaz-create-portfolio-repository.ts
> +    midazId: string,
Não esta enviando o midazId para o midaz, precisa incluir no header.

2024-12-11 21:22 UTC, augusto-draxx commented on src/lib/logger/request-context.ts
> +      // switch (event.level) {
Remover comentários.

2024-12-11 21:25 UTC, augusto-draxx requested changes
Verificar comentários.

2024-12-12 02:54 UTC, paulofdev commented on src/app/api/organizations/[id]/ledgers/[ledgerId]/portfolios/[portfolioId]/route.ts
> +        console.error('Error deleting portfolio', error)
removed

2024-12-12 02:54 UTC, paulofdev commented on src/app/api/organizations/[id]/ledgers/[ledgerId]/portfolios/[portfolioId]/route.ts
> +        console.error('Error updating portfolio', error)
removed

2024-12-12 02:54 UTC, paulofdev commented on src/core/application/mappers/portfolio-mapper.ts
> +import { RequestContextManager } from '@/lib/logger/request-context'
removed

2024-12-12 02:56 UTC, paulofdev commented on src/lib/logger/request-context.ts
> +      // switch (event.level) {
removed

2024-12-12 02:56 UTC, paulofdev commented on src/core/infrastructure/midaz/portfolios/midaz-create-portfolio-repository.ts
> +    midazId: string,
fixed

2024-12-12 02:56 UTC, paulofdev commented on src/core/infrastructure/midaz/portfolios/midaz-update-portfolio-repository.ts
> +        'X-Midaz-Id': midazId
fixed

2024-12-12 14:08 UTC, augusto-draxx approved these changes

2025-01-11 03:20 UTC, closed without merging