Feat/accounts and portfolios
LerianStudio/midaz-console pull request #70
Opened 2024-12-03 22:20 UTC by gabrielcastr0

# Midaz Console Pull Request Checklist

- Implements the functionality to fetch accounts along with their associated portfolios, including accounts without portfolios and vice versa.
- Updates the optional and required fields in the create accounts payload.

## Pull Request Type

[//]: # 'Check the appropriate box for the type of pull request.'

- [x] UI
- [x] Core (Business Lógic)
- [ ] Security
- [ ] internationalization
- [ ] Pipeline
- [ ] Documentation

## Checklist

Please check each item after it's completed.

- [x] I have tested these changes locally.
- [ ] I have updated the documentation accordingly.
- [ ] I have added necessary comments to the code, especially in complex areas.
- [x] I have ensured that my changes adhere to the project's coding standards.
- [ ] I have checked for any potential security issues.
- [ ] I have ensured that all tests pass.
- [ ] I have updated the version appropriately (if applicable).
- [x] I have confirmed this code is ready for review.

## Additional Notes

[//]: # 'Add any additional notes, context, or explanation that could be helpful for reviewers.'

## Obs: Please, always remember to target your PR to develop branch instead of main.

2024-12-03 22:39 UTC, paulofdev commented on src/app/(routes)/ledgers/[id]/accounts/accounts-tab-content.tsx
desmembrar esse arquivo

2024-12-03 22:39 UTC, paulofdev commented on src/app/(routes)/ledgers/[id]/portfolios/portfolios-tab-content.tsx
desmembrar esse arquivo como em accounts

2024-12-03 22:59 UTC, paulofdev approved these changes

2024-12-04 13:26 UTC, caioaletroca commented on src/core/application/use-cases/portfolios-with-accounts/fetch-portfolios-with-account-use-case.tsx
> +    const allAccountsResult = await this.fetchAllAccountsRepository.fetchAll(
This is not going to work on the long run without a portfolioId filter on the accounts listing endpoint on midaz.

2024-12-04 13:57 UTC, caioaletroca commented
@gabrielcastr0  I noticed that intl keys changed but there isn't any translation files changes.
Please run the extract, and using this opportunity, run test, lint and build too to check if everything is fine.

2024-12-04 14:01 UTC, caioaletroca requested changes
Thanks for that overhaul!!!

2024-12-04 14:01 UTC, caioaletroca commented on src/types/accounts-type.ts
> +  portfolio: {
Create a Portfolio type on another file, import it here and use:

``` ts
{
 //...
 portfolio: Pick<PortfolioType, "name">
 //...
}
```

2024-12-04 17:03 UTC, caioaletroca approved these changes

2024-12-04 17:32 UTC, merged